version: '3'
services:
  react:
    container_name: react
    image: node:20
    working_dir: /app
    env_file:
      - .env
    entrypoint: ["/bin/sh","-c"]
    command: 
    - |
      npm install &&
      npm run build &&
      npm start
    volumes:
      - node_modules:/app/node_modules
      - npm_cache:/root/.npm
      - npm_dist:/app/dist
      - .:/app
    ports:
      - "3007:3007"
    # stdin_open: true
    # tty: true
volumes:
  node_modules:
  npm_cache:
  npm_dist:

